# vim: ts=2:sw=2

varSeps: "<>"
format: "%{S0}%{l}<stdin> %{r}<gmail> <volume> <wifi> <bat1> <time> <layout>%{O6}"
plugins:
  volume:
    path: "$GOPATH/src/github.com/pltanton/yags-volume/yags-volume.so"
    sink: "/org/pulseaudio/core1/sink0"
    high: " <vol>%"
    medium: " <vol>%"
    low: " <vol>%"
    muted: "%{F#373b41} <vol>%%{F-}"
  bat1:
    path: "$GOPATH/src/github.com/pltanton/yags-battery/yags-battery.so"
    name: "BAT1"
    high: " <lvl>%"
    medium: " <lvl>%"
    low: " <lvl>%"
    empty: "%{F#a3685a} <lvl>%%{F-}"
    ac: "%{F#b5bd68} <lvl>%%{F-}"
  stdin:
    path: "$GOPATH/src/github.com/pltanton/yags-stdin/yags-stdin.so"
  time:
    path: "$GOPATH/src/github.com/pltanton/yags-timer/time/time.so"
    # timeFormat: "Jan 2 15:04:05" # default
    # pause: 1000 # default
  layout:
    path: "$GOPATH/src/github.com/pltanton/yags-kbdd/yags-kbdd.so"
    names: ["en", "ru"]
  wifi:
    path: "$GOPATH/src/github.com/pltanton/yags-timer/wifi/wifi.so"
    connected: " <lvl>%"
    disconnected: " N/A"
    interface: "wlp4s0"
    pause: 2000
  gmail:
    path: "$GOPATH/src/github.com/pltanton/yags-maildir/yags-maildir.so"
    dir: "/home/anton/mail/gmail/INBOX/"
    filled: "%{F#81a2be}%{F-} <new>"
    empty: "%{F#373b41} <new>%{F-}"
