# vim: ts=2:sw=2

varSeps: "<>"
format: "%{S0}%{l}<stdin> %{r}<gmail> <volume> <wifi> <bat1> <time> <layout>%{O6}"
plugins:
  volume:
    type: "volume"
    high: " <vol>%"
    medium: " <vol>%"
    low: " <vol>%"
    muted: "%{F#373b41} <vol>%%{F-}"
  bat1:
    type: "battery"
    name: "BAT1"
    high: " <lvl>%"
    medium: " <lvl>%"
    low: " <lvl>%"
    empty: "%{F#a3685a} <lvl>%%{F-}"
    ac: "%{F#b5bd68} <lvl>%%{F-}"
  time:
    type: "time"
    # timeFormat: "Jan 2 15:04:05" # default
    # pause: 1000 # default
  layout:
    type: "kbdd"
    names: ["en", "ru"]
  wifi:
    type: "wifi"
    connected: " <lvl>%"
    disconnected: " N/A"
    interface: "wlp4s0"
    pause: 2000
  gmail:
    type: "maildir"
    dir: "/home/anton/mail/gmail/INBOX/"
    filled: "%{F#81a2be}%{F-} <new>"
    empty: "%{F#373b41} <new>%{F-}"
