# vim: ts=2:sw=2

varSeps: "{}"
format: "{volume} {wifi} {bat1} {time} {layout}"
plugins:
  volume:
    path: "$GOPATH/src/github.com/pltanton/yags-volume/yags-volume.so"
    sink: "/org/pulseaudio/core1/sink0"
    high: " {vol}"
    medium: " {vol}"
    low: " {vol}"
    muted: " {vol}"
  bat1:
    path: "$GOPATH/src/github.com/pltanton/yags-battery/yags-battery.so"
    name: "BAT1"
    format: "{icon} {lvl}"
    acFormat: "<span color='#b5bd68'>{icon} {lvl}</span>"
    animationTick: 1000ms
    full: 99
    icons:
      - 
      - 
      - 
      - 
      - 
  time:
    path: "$GOPATH/src/github.com/pltanton/yags-timer/time/time.so"
    # timeFormat: "Jan 2 15:04:05" # default
    # pause: 1000 # default
  layout:
    path: "$GOPATH/src/github.com/pltanton/yags-kbdd/yags-kbdd.so"
    names: ["en", "ru"]
  wifi:
    path: "$GOPATH/src/github.com/pltanton/yags-timer/wifi/wifi.so"
    connected: " {lvl}"
    disconnected: " N/A"
    interface: "wlp4s0"
    pause: 2000
