# vim: ts=2:sw=2

varSeps: "{}"
format: "{gmail} {volume} {wifi} {bat1} {time} {layout}"
plugins:
  volume:
    path: "$GOPATH/src/github.com/pltanton/yags-volume/volume.so"
    sink: "/org/pulseaudio/core1/sink0"
    high: " {vol}%"
    medium: " {vol}%"
    low: " {vol}%"
    muted: "<fc=#373b41> {vol}%</fc>"
  bat1:
    path: "$GOPATH/src/github.com/pltanton/yags-battery/battery.so"
    name: "BAT1"
    high: " {lvl}%"
    medium: " {lvl}%"
    low: " {lvl}%"
    empty: "<fc=#a3685a> {lvl}%</fc>"
    ac: "<fc=#b5bd68> {lvl}%</fc>"
  time:
    path: "$GOPATH/src/github.com/pltanton/yags-timer/time/time.so"
    # timeFormat: "Jan 2 15:04:05" # default
    # pause: 1000 # default
  layout:
    path: "$GOPATH/src/github.com/pltanton/yags-kbdd/kbdd.so"
    names: ["en", "ru"]
  wifi:
    path: "$GOPATH/src/github.com/pltanton/yags-timer/wifi/wifi.so"
    connected: " {lvl}%"
    disconnected: " N/A"
    interface: "wlp4s0"
    pause: 2000
  gmail:
    path: "$GOPATH/src/github.com/pltanton/yags-maildir/maildir.so"
    dir: "/home/anton/mail/gmail/INBOX/"
    filled: "<fc=#81a2be></fc> {new}"
    empty: "<fc=#373b41> {new}</fc>"
